# Constants and Configuration defaults for HealthApp

# Theme (Luxury Minimal Dark)
TH = {
    "bg": "#0d0d0f",  # Pure minimalist dark
    "bg2": "#161619",  # Subtle card background
    "bg3": "#212124",  # Active element background
    "accent": "#00df77",  # Mint Green Accent
    "accent_hover": "#32e896",
    "fg": "#f5f5f7",  # Crisp, readable white
    "fg_dim": "#86868b",  # Elegant muted text
    "success": "#34c759",  # Refined green
    "warning": "#ff9f0a",  # Refined orange
    "danger": "#ff453a",  # Refined red
    "border": "#2c2c2e",  # Subtle borders
    "border_glow": "#48484a",  # Soft glow
}

# Media Key Constants
VK_MEDIA_PLAY_PAUSE = 0xB3
KEYEVENTF_EXTENDEDKEY = 0x0001
KEYEVENTF_KEYUP = 0x0002

# Health Tips
HEALTH_TIPS = {
    "breathing": [
        "Take a slow, deep breath in for 4 seconds, hold for 4, and exhale for 4. 🫁",
        "Deep breathing increases oxygen flow and induces a state of calm. 🧘",
        "Inhale peace, exhale tension. Let your belly rise with each breath. 🌬️",
    ],
    "eye_care": [
        "Look away from the screen! Focus on an object 20 feet away for 20 seconds. 👁️",
        "Blink slowly and deliberately 10 times to rehydrate your eyes. 💧",
        "Gently roll your eyes in circles to relieve strain on the eye muscles. 🌀",
        "Adjust screen brightness so it matches the ambient lighting around you. 💡",
    ],
    "posture": [
        "Sit up straight! Align your ears with your shoulders. 📐",
        "Relax your shoulders away from your ears. Check your spine alignment. 🧘",
        "Make sure your feet are flat on the floor and your knees are at 90 degrees. 🦶",
        "Adjust your chair height so your screen is at eye level. 🖥️",
    ],
    "stretch": [
        "Clasp your hands and stretch them high above your head. 🤸",
        "Rotate your neck slowly to the left, then to the right to release tension. 🔄",
        "Do a gentle torso twist in your chair to stretch your lower back. 🪑",
        "Stand up and stretch your arms and legs. Hold for 15 seconds. 🚶",
    ],
    "hydration": [
        "Time for a sip of water! Stay hydrated to keep your mind sharp. 💧",
        "Drink a glass of water. Proper hydration keeps fatigue at bay. 🥛",
        "Keep a water bottle on your desk and take a sip every few minutes. 🐳",
    ],
    "mental": [
        "Take a 10-second mental pause. Let go of all work thoughts. 🧠",
        "Acknowledge one thing you're grateful for right now. 💖",
        "Smile! Even a forced smile can reduce stress hormones. 😊",
        "Take a deep breath and clear your mind of any clutter. 🧘",
    ],
    "hands_wrists": [
        "Shake out your hands and fingers to relieve typing strain. 🖐️",
        "Stretch your wrists: gently pull your fingers back with your other hand. 🫳",
        "Make gentle fists and rotate your wrists clockwise and counter-clockwise. ✊",
        "Massage the palms of your hands to release muscular tension. 💆",
    ],
}

# Default Settings
DEFAULT_SETTINGS = {
    "short_break_interval_min": 20,
    "short_break_duration_sec": 15,
    "long_break_interval_min": 60,
    "long_break_duration_sec": 60,
    "pre_warning_sec": 30,
    "enable_sound": True,
    "enable_dimming": True,
    "enable_weather_warmth": True,
    "latitude": 13.08,
    "longitude": 80.27,
    "paused": False,
    "night_light_start_hour": 18,
    "night_light_end_hour": 6,
    "run_during_game": True,
    "toast_pos": "Center",
    "toast_custom_x": 100,
    "toast_custom_y": 100,
    "toast_width": 260,
    "toast_height": 60,
    "toast_bg_color": "#252525",
    "toast_fg_color": "#ffffff",
    "toast_accent_color": "#00f0ff",
    "toast_font_size": 11,
    "toast_font_weight": "bold",
    "toast_font_family": "Segoe UI",
    "toast_emoji": "👁️",
    "toast_radius": 16,
    "toast_padding_x": 12,
    "toast_padding_y": 10,
    "toast_anim_style": "Slide",
    "toast_opacity": 0.92,
    "toast_border_width": 0,
    "toast_border_color": "#00f0ff",
    "toast_gradient": False,
    "toast_gradient_end": "#101625",
    "toast_shadow": True,
    "toast_accent_stripe": False,
    "toast_text_align": "left",
    "toast_auto_dismiss": True,
    "toast_click_action": "dismiss",
    "toast_progress_bar": False,
    "toast_enable_sound": True,
    "toast_sound_effect": "mac_connect",
    "toast_volume": 80,
    "toast_border_style": "Solid",
    "toast_stripe_pos": "Left",
    "toast_show_clock": False,
    "wellness_points": 0,
    "current_streak": 0,
    "ht_enabled": True,
    "ht_interval_min": 10,
    "ht_duration_sec": 5,
    "ht_night_enabled": True,
    "ht_night_interval_min": 30,
    "ht_night_duration_sec": 5,
    "ht_night_toast_pos": "Bottom-Right",
    "ht_cat_breathing": True,
    "ht_cat_eye_care": True,
    "ht_cat_posture": True,
    "ht_cat_stretch": True,
    "ht_cat_hydration": True,
    "ht_cat_mental": True,
    "ht_cat_hands_wrists": True,
    "ht_toast_pos": "Right",
    "ht_toast_custom_x": 100,
    "ht_toast_custom_y": 100,
    "ht_toast_width": 280,
    "ht_toast_height": 70,
    "ht_toast_bg_color": "#252525",
    "ht_toast_fg_color": "#ffffff",
    "ht_toast_accent_color": "#00f0ff",
    "ht_toast_font_size": 11,
    "ht_toast_font_weight": "bold",
    "ht_toast_font_family": "Segoe UI",
    "ht_toast_emoji": "💡",
    "ht_toast_radius": 16,
    "ht_toast_padding_x": 12,
    "ht_toast_padding_y": 10,
    "ht_toast_anim_style": "Slide",
    "ht_toast_opacity": 0.92,
    "ht_toast_border_width": 0,
    "ht_toast_border_color": "#00f0ff",
    "ht_toast_gradient": False,
    "ht_toast_gradient_end": "#101625",
    "ht_toast_shadow": True,
    "ht_toast_accent_stripe": False,
    "ht_toast_text_align": "left",
    "ht_toast_auto_dismiss": True,
    "ht_toast_click_action": "dismiss",
    "ht_toast_progress_bar": False,
    "ht_toast_enable_sound": False,
    "ht_toast_sound_effect": "mac_disconnect",
    "ht_toast_volume": 80,
    "ht_toast_border_style": "Solid",
    "ht_toast_stripe_pos": "Left",
    "ht_toast_show_clock": False,
    "bc_enabled": True,
    "bc_start_time": "23:00",
    "bc_end_time": "06:00",
    "bc_target_brightness": 2,
    "bc_duration_minutes": 60,
    "bc_aggressive_target_brightness": 5,
    "bc_aggressive_duration_minutes": 10,
    "bc_transition_time_sec": 5,
    "bc_aggressive_transition_time_sec": 30,
    "bc_safe_brightness": 30,
    "bc_safe_duration_seconds": 30,
    "bc_toast_enable_sound": True,
    "bc_toast_sound_effect": "mac_connect",
    "bc_toast_width": 320,
    "bc_toast_height": 145,
    "bc_toast_bg_color": "#101625",
    "bc_toast_fg_color": "#e2e8f0",
    "bc_toast_accent_color": "#ff2a2a",
    "bc_toast_border_width": 1,
    "bc_toast_border_color": "#7c3aed",
    "bc_toast_radius": 16,
    "bc_toast_gradient": False,
    "bc_toast_gradient_end": "#101625",
    "bc_toast_shadow": True,
    "bc_toast_accent_stripe": False,
    "bc_toast_text_align": "left",
    "bc_toast_progress_bar": False,
    "bc_toast_click_action": "dismiss",
    "bc_toast_border_style": "Solid",
    "bc_toast_stripe_pos": "Left",
    "bc_toast_volume": 80,
    "bc_toast_opacity": 0.95,
    "bc_toast_emoji": "⚠️",
    "bc_toast_padding_x": 12,
    "bc_toast_padding_y": 10,
    "nc_enabled": True,
    "nc_start_time": "23:59",
    "nc_end_time": "06:00",
    "nc_interval_minutes": 5,
    "nc_flick_enabled": True,
    "nc_flick_hold_sec": 1.0,
    "nc_flick_fade_sec": 3.0,
    "nc_slogans": (
        "It's late. Your body needs rest. 🌙|"
        "Go to sleep. Tomorrow is a new day. 💤|"
        "Screen time is over. Time for dream time. ✨|"
        "Rest your eyes and your mind. 🛌|"
        "Sleep is the best meditation. 🧘"
    ),
    "nc_toast_width": 300,
    "nc_toast_height": 80,
    "nc_toast_bg_color": "#0d1117",
    "nc_toast_fg_color": "#c9d1d9",
    "nc_toast_accent_color": "#58a6ff",
    "nc_toast_font_size": 12,
    "nc_toast_font_weight": "bold",
    "nc_toast_font_family": "Segoe UI",
    "nc_toast_emoji": "🌙",
    "nc_toast_radius": 12,
    "nc_toast_padding_x": 15,
    "nc_toast_padding_y": 15,
    "nc_toast_anim_style": "Slide",
    "nc_toast_opacity": 0.95,
    "nc_toast_border_width": 2,
    "nc_toast_border_color": "#30363d",
    "nc_toast_enable_sound": True,
    "nc_toast_sound_effect": "mac_connect",
    "nc_toast_gradient": False,
    "nc_toast_gradient_end": "#101625",
    "nc_toast_shadow": True,
    "nc_toast_accent_stripe": False,
    "nc_toast_text_align": "left",
    "nc_toast_progress_bar": False,
    "nc_toast_click_action": "dismiss",
    "nc_toast_border_style": "Solid",
    "nc_toast_stripe_pos": "Left",
    "nc_toast_volume": 80,
    "nl_enabled": True,
    "nl_day_temp": 6500,
    "nl_night_temp": 3500,
    "nl_transition_duration": 20,
    "break_audio_source": "default",
    "voice_prompts_enabled": False,
    "voice_inhale_sec": 4,
    "voice_hold_in_sec": 4,
    "voice_exhale_sec": 4,
    "voice_hold_out_sec": 4,
    "voice_volume": 80,
    "voice_rate": 0,
    "voice_inhale_text": "Breathe in",
    "voice_exhale_text": "Breathe out",
    "voice_hold_in_text": "Hold",
    "voice_hold_out_text": "Hold",
    "voice_break_type": "Both",
    "voice_min_duration_sec": 15,
    "voice_name": "Default",
    "location_check_interval_hours": 1,
    "bc_skip_until": 0.0,
    "voice_start_delay_sec": 3,
    "voice_pitch": 0,
}

SOUND_EFFECTS = [
    "cyber_alert",
    "retro_beep",
    "zen_bowl",
    "echo_ping",
    "digital_chime",
    "sci_fi_sweep",
    "soft_click",
    "tech_chirp",
    "bubble_pop",
    "crystal_bell",
    "ambient_pulse_8d",
    "space_echo_8d",
    "zen_harmony_8d",
    "SystemAsterisk",
    "SystemExclamation",
    "SystemHand",
    "SystemQuestion",
    "SystemDefault",
]
